---
image:
  repository: ghcr.io/bradfordwagner/vault-k8s-auth
  tag: 2.0.0-debian_bookworm

service_account: vault-auth

context:
  secret:
    # includes
    # server = kubernetes api server address
    # ca = kubernetes api server certificate authority
    # cluster_name = auth endpoint at auth/kubernetes/cluster_name
    # VAULT_TOKEN = secret 0 to bootstrap to vault with - should eventually be an approle
    name: k8s-auth-config

vault:
  address: https://bradfordwagner.com:8200

