---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service_account }}
  labels:
    {{- include "labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: {{ .Values.service_account }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-k8s-auth
  labels:
    {{- include "labels" . | nindent 4 }}
rules:
  - verbs: [get]
    apiGroups: [""]
    resources: [serviceaccounts,secrets]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-k8s-auth
  labels:
    {{- include "labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-k8s-auth
subjects:
  - kind: ServiceAccount
    name: {{ .Values.service_account }}
    namespace: {{ .Release.Namespace }}
